# Generated by Django 5.2.8 on 2025-11-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0002_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion_Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('Pais', models.CharField(max_length=50)),
            ],
        ),
    ]
