# Generated by Django 5.2.8 on 2025-11-11 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0003_direccion_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion_envio',
            name='Cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.cliente'),
        ),
    ]
