# Generated by Django 5.2.8 on 2025-11-11 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0004_direccion_envio_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodo_pago',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='metodo_pago',
            name='fecha_expiracion',
        ),
        migrations.RemoveField(
            model_name='metodo_pago',
            name='tipo_tarjeta',
        ),
        migrations.RemoveField(
            model_name='metodo_pago',
            name='ultimos_digitos',
        ),
        migrations.AddField(
            model_name='metodo_pago',
            name='detalles_pago',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='metodo_pago',
            name='forma_pago',
            field=models.CharField(choices=[('tarjeta_credito', 'tarjeta_credito'), ('qr', 'qr'), ('efectivo', 'efectivo')], default='efectivo', max_length=50),
        ),
        migrations.AddField(
            model_name='metodo_pago',
            name='Cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.cliente'),
        ),
    ]
