# Generated by Django 5.2.8 on 2025-11-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0005_remove_metodo_pago_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodo_pago',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='metodo_pago',
            name='detalles_pago',
        ),
        migrations.RemoveField(
            model_name='metodo_pago',
            name='forma_pago',
        ),
        migrations.AddField(
            model_name='metodo_pago',
            name='tipo_pago',
            field=models.CharField(choices=[('tarjeta_credito', 'tarjeta_credito'), ('qr', 'qr'), ('por_pagar', 'por_pagar')], default='por_pagar', max_length=50, null=True),
        ),
    ]
