# Generated by Django 5.2.8 on 2025-11-14 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0006_remove_metodo_pago_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodo_pago',
            name='Cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.cliente'),
        ),
    ]
