# Generated by Django 5.2.8 on 2025-11-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0007_metodo_pago_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=200),
        ),
    ]
