# Generated by Django 5.2.8 on 2025-11-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0008_alter_cliente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodo_pago',
            name='Cliente',
        ),
    ]
