# Generated by Django 5.2.8 on 2025-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0009_remove_metodo_pago_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion_envio',
            name='codigo_postal',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
