# Generated by Django 5.2.8 on 2025-11-14 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='estado',
        ),
        migrations.AddField(
            model_name='compra',
            name='Proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_compras.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_compra',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
