# Generated by Django 5.2.8 on 2025-11-11 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_Cliente', '0004_direccion_envio_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.cliente')),
                ('direccion_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.direccion_envio')),
            ],
        ),
    ]
