# Generated by Django 5.2.8 on 2025-11-14 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0009_remove_metodo_pago_cliente'),
        ('app_pedidos', '0002_remove_pedido_cliente_pedido_costo_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_envio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.direccion_envio'),
        ),
    ]
