# Generated by Django 5.2.8 on 2025-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedidos', '0003_alter_pedido_direccion_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('online', 'Venta Online'), ('presencial', 'Venta Presencial/POS')], default='online', max_length=20, null=True),
        ),
    ]
