# Generated by Django 5.2.8 on 2025-11-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0004_direccion_envio_cliente'),
        ('app_productos', '0002_productocategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto_url', models.URLField()),
                ('texto', models.CharField(max_length=200)),
                ('es_principal', models.BooleanField(default=False)),
                ('Producto_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.productocategoria')),
            ],
        ),
        migrations.CreateModel(
            name='reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha_reseña', models.DateTimeField(auto_now_add=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.cliente')),
                ('Producto_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.productocategoria')),
            ],
        ),
    ]
