# Generated by Django 5.2.8 on 2025-11-11 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_compras', '0001_initial'),
        ('app_productos', '0003_imagen_producto_reseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_compras.compra')),
                ('producto_variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.productocategoria')),
            ],
        ),
        migrations.CreateModel(
            name='item_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('Producto_variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.productocategoria')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_compras.compra')),
            ],
        ),
    ]
