# Generated by Django 5.2.8 on 2025-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0004_item_compras_item_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen_producto',
            name='Producto_url',
        ),
        migrations.AddField(
            model_name='imagen_producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
