# Generated by Django 5.2.8 on 2025-11-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0005_remove_imagen_producto_producto_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocategoria',
            name='capacidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
