# Generated by Django 5.2.8 on 2025-11-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0006_alter_productocategoria_capacidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entradas', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('stock_maximo', models.IntegerField()),
                ('ubicacion_almacen', models.CharField(max_length=100)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('Producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.producto')),
            ],
        ),
    ]
