# Generated by Django 5.2.8 on 2025-11-14 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0006_remove_metodo_pago_cliente_and_more'),
        ('app_productos', '0007_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='productocategoria',
            name='producto',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='cantidad_entradas',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='peso',
        ),
        migrations.AddField(
            model_name='item_compras',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item_compras',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item_pedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item_pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_productos.categoria'),
        ),
        migrations.RenameModel(
            old_name='reseña',
            new_name='Comentarios',
        ),
        migrations.CreateModel(
            name='Producto_Variantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.producto')),
            ],
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='Producto_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.producto_variantes'),
        ),
        migrations.AlterField(
            model_name='imagen_producto',
            name='Producto_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.producto_variantes'),
        ),
        migrations.AlterField(
            model_name='item_compras',
            name='producto_variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.producto_variantes'),
        ),
        migrations.AlterField(
            model_name='item_pedido',
            name='Producto_variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.producto_variantes'),
        ),
    ]
