# Generated by Django 5.2.8 on 2025-11-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_carrito', '0004_alter_itemcarrito_producto_variante'),
        ('app_productos', '0008_remove_productocategoria_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoCategoria',
        ),
    ]
