# Generated by Django 5.2.8 on 2025-11-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0009_delete_productocategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='Producto_id',
        ),
        migrations.AddField(
            model_name='producto_variantes',
            name='Inventario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_productos.inventario'),
        ),
    ]
