# Generated by Django 5.2.8 on 2025-11-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_carrito', '0001_initial'),
        ('app_productos', '0003_imagen_producto_reseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.producto')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_carrito.carrito')),
            ],
        ),
    ]
