# Generated by Django 5.2.8 on 2025-11-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_carrito', '0002_itemcarrito'),
        ('app_productos', '0007_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='Producto',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='producto_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_productos.productocategoria'),
        ),
    ]
