# Generated by Django 5.2.8 on 2025-11-14 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_carrito', '0003_remove_itemcarrito_producto_and_more'),
        ('app_productos', '0008_remove_productocategoria_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_productos.producto_variantes'),
        ),
    ]
